In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
scalar = 4.3
arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8])

print("Scalar: ", scalar)
print("Array: ", arr)

add_scalar = scalar + arr
sub_scalar = scalar - arr
mul_scalar = scalar * arr
div_scalar = scalar / arr

print("Addition: ", add_scalar)
print("Subtraction: ", sub_scalar)
print("Multiplication: ", mul_scalar)
print("Division: ", div_scalar)

abs_values = np.abs(arr)
print("Absolute value:", abs_values)

sqrt_values = np.sqrt(arr)
print("Squer root:", sqrt_values)

exp_values = np. exp(arr)
print("Exponential: ", exp_values)

log_values = np.log(arr)
print("Natural logarithm: ", log_values)

Logarithm_base_values = np.log10(arr)
print("Logarithm base 10: ", Logarithm_base_values)

sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan", atan_values)

Scalar:  4.3
Array:  [1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8]
Addition:  [5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1]
Subtraction:  [3.2 3.1 3.  2.9 2.8 2.7 2.6 2.5]
Multiplication:  [4.73 5.16 5.59 6.02 6.45 6.88 7.31 7.74]
Division:  [3.90909091 3.58333333 3.30769231 3.07142857 2.86666667 2.6875
 2.52941176 2.38888889]
Absolute value: [1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8]
Squer root: [1.04880885 1.09544512 1.14017543 1.18321596 1.22474487 1.26491106
 1.30384048 1.34164079]
Exponential:  [3.00416602 3.32011692 3.66929667 4.05519997 4.48168907 4.95303242
 5.47394739 6.04964746]
Natural logarithm:  [0.09531018 0.18232156 0.26236426 0.33647224 0.40546511 0.47000363
 0.53062825 0.58778666]
Logarithm base 10:  [0.04139269 0.07918125 0.11394335 0.14612804 0.17609126 0.20411998
 0.23044892 0.25527251]
sin: [0.89120736 0.93203909 0.96355819 0.98544973 0.99749499 0.9995736
 0.99166481 0.97384763]
cos: [ 0.45359612  0.36235775  0.26749883  0.16996714  0.0707372  -0.02919952
 -0.12884449 -0.22720209]
tan: [  1.964759

In [15]:
matrix = np.array([[1.1, 1.2, -14.3], [1.4, 1.5, -17.6], [1.7, 1.8, 1.9], [2.1, 2.2, -21.3]])

print("Matrix: ", matrix)

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)

print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)

asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

print("asin:", asin_values)
print("acos:", acos_values)
print("atan", atan_values)

exp_values = np. exp(matrix)
print("Exponential: ", exp_values)

log_values = np.log(matrix)
print("Natural logarithm: ", log_values)

Logarithm_base_values = np.log10(matrix)
print("Logarithm base 10: ", Logarithm_base_values)

abs_values = np.abs(matrix)
print("Absolute value:", abs_values)

sqrt_values = np.sqrt(matrix)
print("Squer root:", sqrt_values)

rem_values = np.remainder(matrix, 3)
print("Reminder:", rem_values)

floor_values = np.floor(matrix)
print("floor:", floor_values)
ceil_values = np.ceil(matrix)
print("ceil:", ceil_values)

Matrix:  [[  1.1   1.2 -14.3]
 [  1.4   1.5 -17.6]
 [  1.7   1.8   1.9]
 [  2.1   2.2 -21.3]]
sin: [[ 0.89120736  0.93203909 -0.98677196]
 [ 0.98544973  0.99749499  0.9488445 ]
 [ 0.99166481  0.97384763  0.94630009]
 [ 0.86320937  0.8084964  -0.6374226 ]]
cos: [[ 0.45359612  0.36235775 -0.16211444]
 [ 0.16996714  0.0707372   0.31574375]
 [-0.12884449 -0.22720209 -0.32328957]
 [-0.5048461  -0.58850112 -0.7705144 ]]
tan: [[ 1.96475966  2.57215162  6.0868852 ]
 [ 5.79788372 14.10141995  3.00510931]
 [-7.69660214 -4.28626167 -2.92709751]
 [-1.70984654 -1.37382306  0.8272689 ]]
asin: [[ 0.52359878  0.57693135 -1.57079633]
 [ 0.689775    0.75024524 -1.57079633]
 [ 0.88312667  0.95824159  1.04243906]
 [ 1.26813105  1.57079633 -1.57079633]]
acos: [[1.04719755 0.99386498 3.14159265]
 [0.88102133 0.82055108 3.14159265]
 [0.68766965 0.61255474 0.52835726]
 [0.30266527 0.         3.14159265]]
atan [[ 0.83298127  0.87605805 -1.50097991]
 [ 0.95054684  0.98279372 -1.51403917]
 [ 1.03907226  1.063697

/tmp/ipykernel_1037/747364909.py:24: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)
/tmp/ipykernel_1037/747364909.py:27: RuntimeWarning: invalid value encountered in log10
  Logarithm_base_values = np.log10(matrix)
/tmp/ipykernel_1037/747364909.py:33: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)
